name: Mi primer workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Mensaje de bienvenida
          run: echo "Mi primer Job de GitHub Action"

        - name: Mostrar archivos
          run: ls

        - name: Leer archivo
          run: cat README.md