name: Mi primer workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout action
          uses: actions/checkout@v4

        - name: Listar y leer archivo
          run: |
            echo "Mi primer Job de GitHub Action"
            ls -ltra
            cat README.md

        - name: Generate ASCII work
          run: cowsay -f dragon "Corre por tu vida... Yo soy un dragon RAAAAWR" >> dragon.txt

#        - name: Mostrar archivos
#          run: ls

#        - name: Leer archivo
#          run: cat README.md