name: Generate ASCII artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Corre por tu vida, soy un dragon RAAAAWR" >> dragon.txt

    - name: Test file exist
      run: grep -i "dragon" dragon.txt

    - name: Read File
      run: cat dragon.txt

    - name: List Repo files
      run: ls -ltra