name: Generate ASCII artwork

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install and run cowsay
      run: |
        sudo apt-get install cowsay -y
        cowsay -f dragon "Corre por tu vida, soy un dragon RAAAAWR" >> dragon.txt

    - name: Upload dragon file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download dragon file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file

    - name: Test file exist
      run: grep -i "dragon" dragon.txt
    
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download dragon file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file    

    - name: Read and Deploy
      run: |
        cat dragon.txt
        echo deploying ... .. .