name: Generate ASCII artwork

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install and run cowsay
      run: |
        sudo apt-get install cowsay -y
        cowsay -f dragon "Corre por tu vida, soy un dragon RAAAAWR" >> dragon.txt
        sleep 10

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Test file exist
      run: |
        sleep 10
        grep -i "dragon" dragon.txt
    
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Read and Deploy
      run: |
        cat dragon.txt
        echo deploying ... .. .