name: Workflow filters and activities

on:
    workflow_dispatch: 
    
    push:
        branches: 
            - main
            - '!feature/*'
    
    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this wokflow was executed for event type - ${{ github.event_name }}